version: "3.1"
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: 10.0.134.183
      WORDPRESS_DB_USER: w_user
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - /mnt/wordpress:/var/www/html